### ISSUE TITLE
[優先度　中]　auction/keeper/keeper_test.go test修正

### ISSUE THREAD

**Issue by Tomosuke0930** [lcnem/jpyx#70]
```
Running tool: /Users/tom/.goenv/versions/1.16.4/bin/go test -timeout 30s -run ^TestIterateAuctions$ github.com/lcnem/jpyx/x/auction/keeper

# github.com/keybase/go-keychain
cgo-gcc-prolog:203:11: warning: 'SecTrustedApplicationCreateFromPath' is deprecated: first deprecated in macOS 10.15 - No longer supported [-Wdeprecated-declarations]
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/Security.framework/Headers/SecTrustedApplication.h:59:10: note: 'SecTrustedApplicationCreateFromPath' has been explicitly marked deprecated here
--- FAIL: TestIterateAuctions (0.00s)
panic: interface conversion: interface is nil, not types.Auction [recovered]
	panic: interface conversion: interface is nil, not types.Auction

goroutine 67 [running]:
testing.tRunner.func1.2(0x1015996a0, 0x14001044660)
	/Users/tom/.goenv/versions/1.16.4/src/testing/testing.go:1143 +0x25c
testing.tRunner.func1(0x14000183c80)
	/Users/tom/.goenv/versions/1.16.4/src/testing/testing.go:1146 +0x384
panic(0x1015996a0, 0x14001044660)
	/Users/tom/.goenv/versions/1.16.4/src/runtime/panic.go:965 +0x14c
github.com/lcnem/jpyx/x/auction/keeper.Keeper.IterateAuctions(0x1017cc238, 0x14000ee10c0, 0x10179dbf8, 0x14000f0a370, 0x10179dbf8, 0x0, 0x1017c7a88, 0x14000ee10c0, 0x140001aecd8, 0x10179dbf8, ...)
	/Users/Tom/Desktop/Works/lcnem/cosmos/jpyx/x/auction/keeper/keeper.go:175 +0x168
github.com/lcnem/jpyx/x/auction/keeper_test.TestIterateAuctions(0x14000183c80)
	/Users/Tom/Desktop/Works/lcnem/cosmos/jpyx/x/auction/keeper/keeper_test.go:87 +0x7b4
testing.tRunner(0x14000183c80, 0x10175e778)
	/Users/tom/.goenv/versions/1.16.4/src/testing/testing.go:1193 +0xe0
created by testing.(*T).Run
	/Users/tom/.goenv/versions/1.16.4/src/testing/testing.go:1238 +0x21c
FAIL	github.com/lcnem/jpyx/x/auction/keeper	0.289s
FAIL
```

**Comment by KimuraYu45z** [comment]
@Tomosuke0930 コードブロック化しておきました
以後お願いします

**Comment by KimuraYu45z** [comment]
issueの本文の話

**Comment by KimuraYu45z** [comment]
```
# github.com/keybase/go-keychain
cgo-gcc-prolog:203:11: warning: 'SecTrustedApplicationCreateFromPath' is deprecated: first deprecated in macOS 10.15 - No longer supported [-Wdeprecated-declarations]
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/Security.framework/Headers/SecTrustedApplication.h:59:10: note: 'SecTrustedApplicationCreateFromPath' has been explicitly marked deprecated here
```

これはmac特有の警告（エラーじゃない）ので以後無視で。
ここは

**Comment by KimuraYu45z** [comment]
```
panic: interface conversion: interface is nil, not types.Auction [recovered]
```

ここが肝

**Comment by Tomosuke0930** [comment]
こちら松岡さんと相談した結果、一度保留してほかのIssueに取り掛かります

**Comment by KimuraYu45z** [comment]
これたぶんいまおれらでやってるの治ったらなおります

**Comment by Tomosuke0930** [comment]
承知しました！よろしくお願いいたします
