### ISSUE TITLE
[優先度 中] incentive/keeper/keeper_test.go test修正 

### ISSUE THREAD

**Issue by Tomosuke0930** [lcnem/jpyx#73]
123 行目　func TestKeeperTestSuiteにて

```
Running tool: /usr/local/go/bin/go test -timeout 30s -run ^TestKeeperTestSuite$ github.com/lcnem/jpyx/x/incentive/keeper

--- FAIL: TestKeeperTestSuite (0.01s)
    --- FAIL: TestKeeperTestSuite/TestAccumulateJpyxMintingRewards (0.01s)
        --- FAIL: TestKeeperTestSuite/TestAccumulateJpyxMintingRewards/7_seconds (0.00s)
panic: bad Duration: time: missing unit in duration "1814400000000000" [recovered]
	panic: bad Duration: time: missing unit in duration "1814400000000000"

goroutine 185 [running]:
testing.tRunner.func1.2({0x512dd00, 0xc0011dc570})
	/usr/local/go/src/testing/testing.go:1209 +0x24e
testing.tRunner.func1()
	/usr/local/go/src/testing/testing.go:1212 +0x218
panic({0x512dd00, 0xc0011dc570})
	/usr/local/go/src/runtime/panic.go:1038 +0x215
github.com/cosmos/cosmos-sdk/codec.(*ProtoCodec).MustUnmarshalJSON(0x0, {0xc0011b0180, 0x0, 0x575c368}, {0x573b300, 0xc0000fd600})
	/Users/tom/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.42.6/codec/proto_codec.go:160 +0x45
github.com/cosmos/cosmos-sdk/x/staking.AppModule.InitGenesis({{{0x5783178, 0xc0010d8480}}, {{0x57324c0, 0xc0010d9680}, {0x577af28, 0xc0010d8480}, {0x5762678, 0xc0010dd8c0}, {0x2ffcf478, 0xc00111c420}, ...}, ...}, ...)
	/Users/tom/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.42.6/x/staking/module.go:148 +0xa2
github.com/cosmos/cosmos-sdk/types/module.(*Manager).InitGenesis(_, {{0x575bf08, 0xc00011e008}, {0x5778db0, 0xc0005b5240}, {{0x0, 0x0}, {0x0, 0x0}, 0x0, ...}, ...}, ...)
	/Users/tom/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.42.6/types/module/module.go:304 +0x29d
github.com/lcnem/jpyx/app.(*App).InitChainer(_, {{0x575bf08, 0xc00011e008}, {0x5778db0, 0xc0005b5240}, {{0x0, 0x0}, {0x0, 0x0}, 0x0, ...}, ...}, ...)
	/Users/Tom/Desktop/Works/lcnem/cosmos/jpyx/app/app.go:547 +0x129
github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).InitChain(0xc000ddbba0, {{0x0, 0x0, 0x0}, {0x0, 0x0}, 0x0, {0x63d9798, 0x0, 0x0}, ...})
	/Users/tom/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.42.6/baseapp/abci.go:62 +0x475
github.com/lcnem/jpyx/app.TestApp.InitializeFromGenesisStates({{0xc000ddbba0, 0xc0000b2de8, {0x5783178, 0xc0010d8480}, {0x576b2a0, 0xc0010b3380}, 0x0, 0xc0010fadb0, 0xc0010fade0, 0xc0010fae10, ...}}, ...)
	/Users/Tom/Desktop/Works/lcnem/cosmos/jpyx/app/test_common.go:115 +0x178
github.com/lcnem/jpyx/x/incentive/keeper_test.(*KeeperTestSuite).SetupWithGenState(0xc000eae000)
	/Users/Tom/Desktop/Works/lcnem/cosmos/jpyx/x/incentive/keeper/integration_test.go:222 +0x2ab
github.com/lcnem/jpyx/x/incentive/keeper_test.(*KeeperTestSuite).TestAccumulateJpyxMintingRewards.func1()
	/Users/Tom/Desktop/Works/lcnem/cosmos/jpyx/x/incentive/keeper/rewards_test.go:67 +0x4e
github.com/stretchr/testify/suite.(*Suite).Run.func1(0xc000ddad00)
	/Users/tom/go/pkg/mod/github.com/stretchr/testify@v1.7.0/suite/suite.go:77 +0xf2
testing.tRunner(0xc000ddad00, 0xc0010b3158)
	/usr/local/go/src/testing/testing.go:1259 +0x102
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:1306 +0x35a
FAIL	github.com/lcnem/jpyx/x/incentive/keeper	1.267s
FAIL

```

**Comment by Senna46** [comment]
package testでpayout_testのエラーが出ているだけで、これのエラーは解決していないですか？
```
Running tool: /usr/local/go/bin/go test -timeout 30s -run ^TestKeeperTestSuite$ -testify.m ^(TestGetSetDeleteJpyxMintingClaim|TestIterateJPYXMintingClaims)$ github.com/lcnem/jpyx/x/incentive/keeper

PASS
ok  	github.com/lcnem/jpyx/x/incentive/keeper	0.067s
```
